### ISSUE TITLE
Request to add license file

### ISSUE THREAD

**Issue by queglay** [arctiqjacob/vault-terraform-demo#1]
Great work on this example, its very helpful, thankyou!  I'd like to use some of it as a template to initialise a deployment and I was wondering if you could associate a license?  I'd like to include it in my own repo which will be available under MPL2.0

Thanks if you can!

**Comment by jacobmammoliti** [comment]
@queglay the issue with adding the license through Terraform here is that it would live in the state file in plaintext. Licensing Vault is usually a one time activity per cluster. If there is a real need to automate it, I'd look at interacting with the [Vault license API ](https://www.vaultproject.io/api-docs/system/license) endpoint with some automation tool and have it take care of the licensing afterwards.

**Comment by queglay** [comment]
Apologies @arctiqjacob, I meant a license file for your repository.

**Comment by jacobmammoliti** [comment]
ah lol.. got it! That is added now, thanks @queglay! Closing this off.
